# Generated by Django 5.1.6 on 2025-03-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlysands', '0002_userprofile_confirmation_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('suburb', models.CharField(blank=True, max_length=255, null=True)),
                ('beach_type', models.JSONField(default=list)),
                ('rating', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)])),
                ('return_visit', models.BooleanField()),
                ('tags', models.JSONField(default=list)),
                ('vibe', models.JSONField(default=list)),
                ('review', models.TextField(blank=True, null=True)),
                ('related_walks', models.JSONField(default=list)),
                ('visited', models.BooleanField()),
                ('other_name', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
