# Generated by Django 5.1.6 on 2025-03-13 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlysands', '0003_beach'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beach',
            options={'verbose_name_plural': 'Beaches'},
        ),
        migrations.RemoveField(
            model_name='beach',
            name='other_name',
        ),
        migrations.AddField(
            model_name='beach',
            name='other_names',
            field=models.JSONField(default=list),
        ),
    ]
