# Generated by Django 5.1.6 on 2025-03-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlysands', '0004_alter_beach_options_remove_beach_other_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beach',
            name='rating',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], null=True),
        ),
    ]
