# Generated by Django 5.1.6 on 2025-03-16 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlysands', '0005_alter_beach_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeachImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='beach_images/')),
                ('beach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='onlysands.beach')),
            ],
        ),
    ]
