repos:
  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: 
          - --profile=black
          - --atomic

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: 
          - --line-length=88
        exclude: ^migrations/|/migrations/
        
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13
    hooks:
      - id: ruff
        args: 
          - --line-length=88
          - --ignore=E203
          - --fix

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.0
    hooks:
      - id: mypy

  - repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        args:
          - --max-line-length=80
          - --extend-ignore=E203,E501,E701
          - --extend-select=B950
        exclude: ^migrations/|/migrations/